#CC=${HOST_GCC}
LIBMOD_DIR=$(TARGET_DIR)/system/lib/amplayer
#export CC BUILD_DIR STAGING_DIR TARGET_DIR LIBMOD_DIR
all:
	mkdir -p $(LIBMOD_DIR)
	cp -rf libdash_mod.so  $(LIBMOD_DIR)/ 

clean:
	rm -rf $(libdashdir)/libdash_mod.so 

